n=list(input().strip())
N=int(''.join(n))
# print(N,n)
cnt= len(n)*(N-int("1"+"0"*(len(n)-1))+1)
# print(cnt)
n.pop()
# print(n)
while n:
    _999 = int('9'*len(n))
    _100 = int('1'+'0'*(len(n)-1))
    # print("ahaha",_999-_100)
    cnt+=len(n)*(_999-_100+1)
    n.pop()
print(cnt)